### PR TITLE
Upgrade the versions for controller-runtime & kube-rbac-proxy (and Operator-sdk)

### PR DESCRIPTION
**Pull request by akshmish**
**What this PR does / why we need it**:

Versions of these libraries need to be updated:

1. [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/tags): Currently this is v0.13.1 (Oct 2022). This can be upgraded to v0.15.1 (Aug 2023)
2. [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy/tags): This has already been flagged on the [repo](https://artifacthub.io/packages/helm/nutanix/ndb-operator?modal=security-report) on artifacthub.io. Latest available is [v0.14.1](https://console.cloud.google.com/gcr/images/kubebuilder/global/kube-rbac-proxy)
3. [Operator-sdk](https://sdk.operatorframework.io/docs/upgrading-sdk-version/version-upgrade-guide/): We should specify a specific version instead of "[latest](https://github.com/nutanix-cloud-native/ndb-operator/actions/runs/5941814844/workflow#L26)"

**How Has This Been Tested?**:
By deploying the operator and provisioning DBs using upgraded versions.

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._
Yes, this PR updates the versions for the above mentioned libraries.

**Release note**:

```release-note
  NONE
```

### CODE REVIEW

File: test/suite_test.go [hunk 1]
```diff
@@ -47,10 +46,6 @@ var testEnv *envtest.Environment
 
 func TestAPIs(t *testing.T) {
 	RegisterFailHandler(Fail)
-
-	RunSpecsWithDefaultAndCustomReporters(t,
```
Comment (akshmish) [inline test/suite_test.go:51]: 0.13.0 -> 0.14.0 does not work because below package was dropped:
[sigs.k8s.io/controller-runtime/pkg/envtest/printer](http://sigs.k8s.io/controller-runtime/pkg/envtest/printer)

We are using this in Gingko tests. 
Reported issue: https://github.com/kubernetes-sigs/controller-runtime/issues/2113

File: api/v1alpha1/database_webhook.go [hunk 2]
```diff
@@ -211,7 +212,7 @@ func instanceSpecValidatorForCreate(instance *Instance, allErrs field.ErrorList,
 }
 
 // ValidateCreate implements webhook.Validator so a webhook will be registered for the type
-func (r *Database) ValidateCreate() error {
+func (r *Database) ValidateCreate() (admission.Warnings, error) {
```
Comment (akshmish) [inline api/v1alpha1/database_webhook.go:215]: This change was needed to upgrade to controller-runtime v0.15.1
Ref: https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation 

Error received without this change:
```
# github.com/nutanix-cloud-native/ndb-operator/api/v1alpha1
api/v1alpha1/database_webhook.go:120:27: cannot use &Database{} (value of type *Database) as admission.Validator value in variable declaration: *Database does not implement admission.Validator (wrong type for method ValidateCreate)
                have ValidateCreate() error
                want ValidateCreate() (admission.Warnings, error)

```

File: go.mod [hunk 3]
```diff
@@ -3,85 +3,77 @@ module github.com/nutanix-cloud-native/ndb-operator
...
-	k8s.io/client-go v0.25.0
-	sigs.k8s.io/controller-runtime v0.13.1
+	github.com/onsi/ginkgo/v2 v2.9.5
+	github.com/onsi/gomega v1.27.7
+	github.com/stretchr/testify v1.8.1
+	go.uber.org/zap v1.24.0
+	k8s.io/api v0.27.2
+	k8s.io/apimachinery v0.27.2
+	k8s.io/client-go v0.27.2
+	sigs.k8s.io/controller-runtime v0.15.1
```
Comment (akshmish) [inline go.mod:15]: We are already upgrading 2 versions (v0.13.1 -> v0.15.1), I think we should not upgrade to v0.16.1 instantly. This may be more useful in the future when we upgrade to v0.16.1 but this is the error I received when I tried to upgrade to v0.16.1

Issues in moving controller-runtime to: v0.16.1


```
go vet ./...
# github.com/nutanix-cloud-native/ndb-operator/api/v1alpha1
vet: api/v1alpha1/webhook_suite_test.go:102:3: unknown field Host in struct literal of type manager.Options
# github.com/nutanix-cloud-native/ndb-operator
vet: ./main.go:78:3: unknown field MetricsBindAddress in struct literal of type manager.Options
make: *** [vet] Error 1
ndb-operator $
```

File: api/v1alpha1/database_webhook.go [hunk 4]
```diff
@@ -224,22 +225,22 @@ func (r *Database) ValidateCreate() error {
...
 }
 
 // ValidateDelete implements webhook.Validator so a webhook will be registered for the type
-func (r *Database) ValidateDelete() error {
+func (r *Database) ValidateDelete() (admission.Warnings, error) {
 	databaselog.Info("validate delete", "name", r.Name)
 
 	// TODO(user): fill in your validation logic upon object deletion.
-	return nil
+	return nil, nil
```
Comment (akshmish) [inline api/v1alpha1/database_webhook.go:245]: These both can be nil as we are not currently validating while UPDATING or DELETING the CRD.

File: config/default/manager_auth_proxy_patch.yaml [hunk 5]
```diff
@@ -16,7 +16,7 @@ spec:
             capabilities:
               drop:
                 - "ALL"
-          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
+          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
```
Comment (akshmish) [inline config/default/manager_auth_proxy_patch.yaml:19]: The latest is v0.14.2, but I would avoid jumping to the latest and greatest, unless we absolutely have to. Currently trying to understand if there are any reported security vulnerabilities for v0.14.2

https://artifacthub.io/packages/helm/nutanix/ndb-operator?modal=security-report

Comment (akshmish) [inline config/default/manager_auth_proxy_patch.yaml:19]: Updating to v0.14.1 as the docker image for v0.14.2 is [not found](https://console.cloud.google.com/gcr/images/kubebuilder/GLOBAL/kube-rbac-proxy:v0.14.1/details?tab=vulnz) on gcr.io

**Comment by manavrajvanshi** [comment]
Can we also test the functionality to verify if the version upgrades did not break anything? 
Otherwise, LGTM!

**Review by yash-ntnx — APPROVED** [review]

**Comment by yash-ntnx** [comment]
I understand we are updating the library verisons but why did we need to update them?

**Comment by akshmish** [comment]
> I understand we are updating the library verisons but why did we need to update them?

We had to update the kube-rbac-proxy as it is flagged as security vulnerability with v0.13.1 on artifacthub.io

Specific versions of operator-sdk works with specific versions of controller-runtime. There may be a breaking change hence 
we need to qualify our ndb-operator repo with a specific version of operator-sdk (inside workflows/release.yaml)

When we set a operator-sdk version, then we need to ensure that a specific controller-runtime version works with it, hence the effort. While we are setting up a specific version, it is best to use a later version, which is what we are doing here in this PR.

**Comment by akshmish** [comment]
Screenshots:

Screenshot 2023-09-06 at 2 40 31 PM

Screenshot 2023-09-06 at 2 40 49 PM

Screenshot 2023-09-06 at 2 41 05 PM

**Review by manavrajvanshi — APPROVED** [review]
As discussed offline, the testing is good. Thanks!
